config/routes.rb
TodoList::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions

  root to: 'projects#index'

  resources :projects do 
    resources :tasks do
    	member do
    		get :up
    		get :down
    	end
    end
  end

  get '/task/:id/toggle', to: "tasks#toggle"
  
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	has_many :tasks, dependent: :destroy
	validates :title, presence: true
	validates :title, uniqueness: true
end

app/models/task.rb
class Task < ActiveRecord::Base

	belongs_to :project

	before_create :init_priority

	validates :title, presence: true
	validates_uniqueness_of :title, scope: :project_id

	def up
		if victim = Task.where(project_id: self.project_id, priority: (self.priority+1)).first
			self.priority, victim.priority = victim.priority, self.priority
			self.save
			victim.save
		end
	end

	def down
		if victim = Task.where(project_id: self.project_id, priority: (self.priority-1)).first
			self.priority, victim.priority = victim.priority, self.priority
			self.save
			victim.save
		end
	end

	private

		def init_priority
			highest_priority_task = Task.where(project_id: self.project_id).order(priority: :desc).first
			self.priority=if highest_priority_task
				highest_priority_task.priority + 1
			else
				0
			end
		end
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :projects, dependent: :destroy

	attr_accessor :password
	before_save :encrypt_password

	validates_confirmation_of :password
	validates_presence_of :password, on: :create
	validates :password, length: { minimum: 6 }
	validates_presence_of :email
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end

	def encrypt_password 
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  	def current_user
  		@current_user ||= User.find(session[:user_id]) if session[:user_id]
  	end
  	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		if current_user 
			@projects=current_user.projects.to_a
			@new_task = Task.new
			@new_project = Project.new
		else
			redirect_to log_in_path
		end
	end

	def create
		@project = current_user.projects.create!(project_params)
		@new_task = Task.new
		send_ajax_respond and return if request.xhr?
		redirect_to root_url
	end

	def edit
		@project = Project.find(params[:id])
	end

	def destroy
		Project.find(params[:id]).destroy
		if request.xhr?
			render nothing: true
		else
			redirect_to root_url
		end
	end

	def update
		if current_user.projects.find(params[:id]).update_attributes(project_params)
			render nothing: true
		else
			
		end
	end

	private

		def send_ajax_respond
			render partial: 'project', locals: {project: @project}, layout: false 
		end

		def project_params
			params.require(:project).permit(:title)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.authenticate(params[:email], params[:password])
  	if user
  		session[:user_id] = user.id
  		redirect_to root_url
  	else
    	flash.now.alert = "Invalid email or password"
    	render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def up
		Task.where(id:params[:id]).first.up
		render nothing: true
	end

	def down
		Task.where(id:params[:id]).first.down
		render nothing: true
	end

	def show
	end

	def toggle
		@task = Task.find(params[:id])
		@task.is_done ^= true
		@task.save!
		render nothing: true, status: "ok"
	end

	def destroy
		Task.find(params[:id]).destroy
		if request.xhr?
			render nothing: true
		else
			redirect_to root_url
		end
	end

	def create
		@task = Task.create!(task_params)
		send_ajax_respond and return if request.xhr?
		redirect_to root_url
	end

	def edit
		@task = Task.find(params[:id])
	end

	def update
		if Task.find(params[:id]).update_attributes(task_params)
			render nothing: true
		else
			#Implement sending error header and procesing it in javascript event listener
		end
	end

	private 
		def send_ajax_respond
			render partial: 'shared/task', locals: {project: @task.project, t: @task}, layout: false 
		end

		def task_params
			params.require(:task).permit(:title, :project_id, :priority, :deadline)
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user].permit(:email, :password, :password_confirmation))
  	if @user.save
  		session[:user_id] = @user.id
  		redirect_to root_path
  	else
  		render new_user_path
  	end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if current_user %>
		<div class="user_nav">
			Logged in as <%= current_user.email %>.
			<%= link_to "Log out", log_out_path %>
		</div>
	<% end %>
	<div class="container text-center">
		<% flash.each do |name, msg| %>
 		<%= content_tag :div, msg, :id => "flash_#{name}" %>
		<% end %>

		<%= yield %>
	</div>
</body>
</html>ш

app/views/projects/_edit_project_form.html.erb
<%= form_for project, html: {class: "invisible edit_project"}, remote: true do |f| %>
	<%= f.text_field :title %>
	<%= f.submit "Update project" %>
<%end%>

app/views/projects/_new_project_form.html.erb
<%= form_for @new_project, remote: true do |f| %>
<div class="input-append">
	<%= f.text_field :title %>
	<button type="submit" class="btn">Create Project</button>
</div>
<%end%>

app/views/projects/_project.html.erb
<div class='project'>

	<%= form_for project, html: {class: "edit_project"}, remote: true do |f| %>
	<%= f.text_field :title, class: "invisible", id: "text#{project.id}" %>
	<label for="<%="text#{project.id}"%>"><%=project.title%></label>
	<%end%>

	<%= link_to "edit", edit_project_path(project), class: 'edit_project_link' %>
	<%= link_to "delete", project_path(project), remote: true, method: :delete, class: "delete_project" %>

	<%= render 'shared/new_task_form', project: project %>

	<%= render 'shared/tasks', project: project %>

	<br><br><br>
</div>

app/views/projects/_projects.html.erb
<div id="projects">
	<%= render partial: 'project', collection: @projects %>
</div>

app/views/projects/index.html.erb
<%= render 'projects' %>

<%= render 'new_project_form' %>

app/views/shared/_edit_task_form.html.erb
<%= form_for [task.project, task], html: {class: "edit_task invisible"}, remote: true do |f| %>
	<%= f.text_field :title %>
	<%= f.submit "Update task" %>
<%end%>

app/views/shared/_new_task_form.html.erb
<%= form_for [project, @new_task], remote: true do |form| %>
		<%= form.hidden_field :project_id, value: project.id %>
		<div class="input-append">
		<%= form.text_field :title %>
		<button type="submit" class="btn">Create Task</button>
		</div>
<%end%>

app/views/shared/_task.html.erb
<div class="task">
	<input type="checkbox" <%= "checked" if t.is_done %> class="done<%=" done_task" if t.is_done%>" id="<%=t.id%>">
	<%= form_for [t.project,t], html: {class: "edit_task"}, remote: true do |f| %>
	<%= f.text_field :title, class: "invisible task_title_input", id: "text_task#{t.id}" %>
	<label for="<%="text_task#{t.id}"%>"><%=t.title%></label>
	<input class="deadline" name="task[deadline]" type="text" value="<%=t.deadline%>" />
	<%end%>
	<%= link_to "up", up_project_task_path(project, t), class: "up", remote: true%>
	<%= link_to "down", down_project_task_path(project, t), class: "down", remote: true%>
	<%= link_to "edit", edit_project_task_path(project, t), class: "edit_task_link" %>
	<%= link_to "delete", project_task_path(project, t),remote: true, method: 'delete', class: "delete_task" %>
</div>

app/views/shared/_tasks.html.erb
<div class="tasks">
	<% project.tasks.order('priority DESC').each do |t| %>
		<%= render 'shared/task', project: project, t: t %>
	<%end%>
</div>

app/views/tasks/edit.html.erb
<%= form_for [@task.project, @task] do |f| %>
	<%= f.text_field :title %>
	<%= f.submit "Update task" %>
<%end%>

app/views/users/new.html.erb
<h1> Sign Up </h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @user.errors.full_messages %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<p>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :password %>
    	<%= f.password_field :password %>
	</p>
	<p>
    	<%= f.label :password_confirmation %>
    	<%= f.password_field :password_confirmation %>
	</p>
	<p><button class="btn" type="submit">Sign Up</button></p>
<% end %>